import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/general/header";

const ibmPlexSans = IBM_Plex_Sans({
  weight: ["100", "300", "600"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable} antialiased bg-slate-100`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
